CREATE TABLE [dbo].[MSO_Reports] (
    [UserID]                               INT           NOT NULL,
    [ReportID]                             INT           NOT NULL,
    [Location_Code]                        FLOAT (53)    NULL,
    [Category_Code]                        FLOAT (53)    NULL,
    [Category_Name]                        VARCHAR (255) NULL,
    [Department_Number]                    VARCHAR (255) NULL,
    [Department_Sub]                       VARCHAR (255) NULL,
    [Flow_Number]                          FLOAT (53)    NULL,
    [Department_Name]                      VARCHAR (255) NULL,
    [Temp_Category_Number]                 VARCHAR (255) NULL,
    [Temp_Category_Name]                   VARCHAR (255) NULL,
    [Avg_Trend]                            FLOAT (53)    NULL,
    [Sales_Quantity]                       FLOAT (53)    NULL,
    [Sales_Value]                          FLOAT (53)    NULL,
    [Profit_Value]                         FLOAT (53)    NULL,
    [Sales_Less_Waste]                     FLOAT (53)    NULL,
    [Org_Sales_Quantity]                   FLOAT (53)    NULL,
    [Org_Sales_Value]                      FLOAT (53)    NULL,
    [Org_Profit_Value]                     FLOAT (53)    NULL,
    [Org_Sales_Less_Waste]                 FLOAT (53)    NULL,
    [Bays]                                 FLOAT (53)    NULL,
    [Min_Bays]                             FLOAT (53)    NULL,
    [Max_Bays]                             FLOAT (53)    NULL,
    [Exclude_from_analysis]                INT           NOT NULL,
    [DoS_Target]                           FLOAT (53)    NOT NULL,
    [Cases_Target]                         FLOAT (53)    NOT NULL,
    [Org_Bays]                             FLOAT (53)    NOT NULL,
    [UnitSalesMix_UserSet]                 FLOAT (53)    NOT NULL,
    [ValueSalesMix_UserSet]                FLOAT (53)    NOT NULL,
    [ProfitSalesMix_UserSet]               FLOAT (53)    NOT NULL,
    [SalesLessWaste_UserSet]               FLOAT (53)    NOT NULL,
    [SalesProfitMix_UserSet]               FLOAT (53)    NOT NULL,
    [SalesMixCube_UserSet]                 FLOAT (53)    NOT NULL,
    [DOSCasePack_UserSet]                  FLOAT (53)    NOT NULL,
    [FixtureDensity_UserSet]               FLOAT (53)    NOT NULL,
    [MixIncCohort_UserSet]                 FLOAT (53)    NOT NULL,
    [BayRoundingThreshold]                 FLOAT (53)    NOT NULL,
    [Category_QuantCont_Pt]                FLOAT (53)    NOT NULL,
    [Depart_QuantCont_Pt]                  FLOAT (53)    NOT NULL,
    [Temp_QuantCont_Pt]                    FLOAT (53)    NOT NULL,
    [Category_ValueCont_Pt]                FLOAT (53)    NOT NULL,
    [Depart_ValueCont_Pt]                  FLOAT (53)    NOT NULL,
    [Temp_ValueCont_Pt]                    FLOAT (53)    NOT NULL,
    [Category_ProfitCont_Pt]               FLOAT (53)    NOT NULL,
    [Depart_ProfitCont_Pt]                 FLOAT (53)    NOT NULL,
    [Temp_ProfitCont_Pt]                   FLOAT (53)    NOT NULL,
    [Category_WasteCont_Pt]                FLOAT (53)    NOT NULL,
    [Depart_WasteCont_Pt]                  FLOAT (53)    NOT NULL,
    [Temp_WasteCont_Pt]                    FLOAT (53)    NOT NULL,
    [Store_PerfMix_Pt]                     FLOAT (53)    NOT NULL,
    [Dept_PerfMix_Pt]                      FLOAT (53)    NOT NULL,
    [Temp_PerfMix_Pt]                      FLOAT (53)    NOT NULL,
    [Store_BaysPerfMix]                    FLOAT (53)    NOT NULL,
    [Dept_BaysPerfMix]                     FLOAT (53)    NOT NULL,
    [Temp_BaysPerfMix]                     FLOAT (53)    NOT NULL,
    [Store_Ranking]                        FLOAT (53)    NOT NULL,
    [Dept_Ranking]                         FLOAT (53)    NOT NULL,
    [Temp_Ranking]                         FLOAT (53)    NOT NULL,
    [Sum_Cubes]                            FLOAT (53)    NOT NULL,
    [Products_Count]                       FLOAT (53)    NOT NULL,
    [Cat_ProdCube_Avg]                     FLOAT (53)    NOT NULL,
    [Store_ProdCube_Avg]                   FLOAT (53)    NOT NULL,
    [Dept_ProdCube_Avg]                    FLOAT (53)    NOT NULL,
    [Temp_ProdCube_Avg]                    FLOAT (53)    NOT NULL,
    [Store_ProdCat_Avg]                    FLOAT (53)    NOT NULL,
    [Dept_ProdCat_Avg]                     FLOAT (53)    NOT NULL,
    [Temp_ProdCat_Avg]                     FLOAT (53)    NOT NULL,
    [Store_ProdCubeRatio]                  FLOAT (53)    NOT NULL,
    [Dept_ProdCubeRatio]                   FLOAT (53)    NOT NULL,
    [Temp_ProdCubeRatio]                   FLOAT (53)    NOT NULL,
    [Store_BaysFlex_PerfMix]               FLOAT (53)    NOT NULL,
    [Dept_BaysFlex_PerfMix]                FLOAT (53)    NOT NULL,
    [Temp_BaysFlex_PerfMix]                FLOAT (53)    NOT NULL,
    [Bays_Req_Target]                      FLOAT (53)    NOT NULL,
    [Org_Bays_Req_Target]                  FLOAT (53)    NOT NULL,
    [Store_DOSCOS_Bays]                    FLOAT (53)    NOT NULL,
    [Dept_DOSCOS_Bays]                     FLOAT (53)    NOT NULL,
    [Temp_DOSCOS_Bays]                     FLOAT (53)    NOT NULL,
    [Store_Bays_Recc]                      FLOAT (53)    NOT NULL,
    [Dept_Bays_Recc]                       FLOAT (53)    NOT NULL,
    [Temp_Bays_Recc]                       FLOAT (53)    NOT NULL,
    [Org_Store_Bays_Recc]                  FLOAT (53)    NOT NULL,
    [Org_Dept_Bays_Recc]                   FLOAT (53)    NOT NULL,
    [Org_Temp_Bays_Recc]                   FLOAT (53)    NOT NULL,
    [DoSTargetAchieved]                    FLOAT (53)    NOT NULL,
    [CaseTargetAchieved]                   FLOAT (53)    NOT NULL,
    [BothTargetAchieved]                   FLOAT (53)    NOT NULL,
    [Store_Projected_Sales_Quantity]       FLOAT (53)    NOT NULL,
    [Store_Projected_Org_Sales_Quantity]   FLOAT (53)    NOT NULL,
    [Store_Projected_Sales_Value]          FLOAT (53)    NOT NULL,
    [Store_Projected_Org_Sales_Value]      FLOAT (53)    NOT NULL,
    [Store_Projected_Profit_Value]         FLOAT (53)    NOT NULL,
    [Store_Projected_Org_Profit_Value]     FLOAT (53)    NOT NULL,
    [Store_Projected_Sales_Less_Waste]     FLOAT (53)    NOT NULL,
    [Store_Projected_Org_Sales_Less_Waste] FLOAT (53)    NOT NULL,
    [Dept_Projected_Sales_Quantity]        FLOAT (53)    NOT NULL,
    [Dept_Projected_Org_Sales_Quantity]    FLOAT (53)    NOT NULL,
    [Dept_Projected_Sales_Value]           FLOAT (53)    NOT NULL,
    [Dept_Projected_Org_Sales_Value]       FLOAT (53)    NOT NULL,
    [Dept_Projected_Profit_Value]          FLOAT (53)    NOT NULL,
    [Dept_Projected_Org_Profit_Value]      FLOAT (53)    NOT NULL,
    [Dept_Projected_Sales_Less_Waste]      FLOAT (53)    NOT NULL,
    [Dept_Projected_Org_Sales_Less_Waste]  FLOAT (53)    NOT NULL,
    [Temp_Projected_Sales_Quantity]        FLOAT (53)    NOT NULL,
    [Temp_Projected_Org_Sales_Quantity]    FLOAT (53)    NOT NULL,
    [Temp_Projected_Sales_Value]           FLOAT (53)    NOT NULL,
    [Temp_Projected_Org_Sales_Value]       FLOAT (53)    NOT NULL,
    [Temp_Projected_Profit_Value]          FLOAT (53)    NOT NULL,
    [Temp_Projected_Org_Profit_Value]      FLOAT (53)    NOT NULL,
    [Temp_Projected_Sales_Less_Waste]      FLOAT (53)    NOT NULL,
    [Temp_Projected_Org_Sales_Less_Waste]  FLOAT (53)    NOT NULL
);


GO

