CREATE TABLE [dbo].[ReportVersionAttributes] (
    [ReportID]                 INT            NOT NULL,
    [ReportOwner]              NVARCHAR (4)   NULL,
    [BranchNumber]             INT            NULL,
    [ReportName]               NVARCHAR (MAX) NULL,
    [PerfStartDate]            INT            NULL,
    [PerfEndDate]              INT            NULL,
    [MacroSpaceDate]           TEXT           NULL,
    [Cohort]                   NVARCHAR (MAX) NULL,
    [CohortStores]             SMALLINT       NULL,
    [BranchName]               NVARCHAR (MAX) NULL,
    [FullBaySize]              DECIMAL (5, 2) CONSTRAINT [DEFAULT_ReportVersionAttributes_FullBaySize] DEFAULT ((100)) NULL,
    [RoundBaySize]             DECIMAL (5, 2) CONSTRAINT [DEFAULT_ReportVersionAttributes_RoundBaySize] DEFAULT ((50)) NULL,
    [UnitOfMeasure]            NVARCHAR (MAX) CONSTRAINT [DEFAULT_ReportVersionAttributes_UnitOfMeasure] DEFAULT ('Centimetres') NULL,
    [DaysTrading]              INT            CONSTRAINT [DEFAULT_ReportVersionAttributes_DaysTrading] DEFAULT ((7)) NULL,
    [ViewbyStoreTempcatDept]   NVARCHAR (MAX) CONSTRAINT [DEFAULT_ReportVersionAttributes_ViewbyStoreTempcatDept] DEFAULT ('T') NULL,
    [MinBaysforMaxRange]       CHAR (1)       CONSTRAINT [DEFAULT_ReportVersionAttributes_MinBaysforMaxRange] DEFAULT ('Y') NULL,
    [UseProductCube]           CHAR (1)       CONSTRAINT [DEFAULT_ReportVersionAttributes_UseProductCube] DEFAULT ('Y') NULL,
    [UseTrend]                 CHAR (1)       CONSTRAINT [DEFAULT_ReportVersionAttributes_UseTrend] DEFAULT ('Y') NULL,
    [UseMinLMtr]               CHAR (1)       CONSTRAINT [DEFAULT_ReportVersionAttributes_UseMinLMtr] DEFAULT ('Y') NULL,
    [UseMaxLMtr]               CHAR (1)       CONSTRAINT [DEFAULT_ReportVersionAttributes_UseMaxLMtr] DEFAULT ('Y') NULL,
    [IncNumberofProducts]      CHAR (1)       CONSTRAINT [DEFAULT_ReportVersionAttributes_IncNumberofProducts] DEFAULT ('Y') NULL,
    [PotentialSalesAdjustment] DECIMAL (5, 4) CONSTRAINT [DEFAULT_ReportVersionAttributes_PotentialSalesAdjustment] DEFAULT ((0.5)) NULL,
    [CubeFlex]                 DECIMAL (5, 4) CONSTRAINT [DEFAULT_ReportVersionAttributes_CubeFlex] DEFAULT ((0.1)) NULL,
    [TopHighlight]             DECIMAL (5, 4) NULL,
    [BottomHighlight]          DECIMAL (5, 4) NULL,
    [UnitSalesMix_UserSet]     FLOAT (53)     NULL,
    [ValueSalesMix_UserSet]    FLOAT (53)     NULL,
    [ProfitSalesMix_UserSet]   FLOAT (53)     NULL,
    [SalesLessWaste_UserSet]   FLOAT (53)     NULL,
    [SalesProfitMix_UserSet]   FLOAT (53)     NULL,
    [SalesMixCube_UserSet]     FLOAT (53)     NULL,
    [DOSCasePack_UserSet]      FLOAT (53)     NULL,
    [FixtureDensity_UserSet]   FLOAT (53)     NULL,
    [MixIncCohort_UserSet]     FLOAT (53)     NULL,
    [SpaceAdjustment]          DECIMAL (5, 4) NULL,
    [ElasticitySalesDiff]      DECIMAL (5, 4) NULL,
    [DensityMetric]            TEXT           NULL,
    [UMDID]                    NVARCHAR (15)  NULL,
    [DoSDefault]               FLOAT (53)     NULL,
    [CasesDefault]             FLOAT (53)     NULL,
    [BayRoundingThreshold]     FLOAT (53)     CONSTRAINT [DEFAULT_ReportVersionAttributes_BayRoundingThreshold] DEFAULT ((2)) NULL,
    [PerfDateExclusions]       NVARCHAR (MAX) NULL,
    [ExcludeCategories]        TEXT           NULL,
    [RefreshTypeNeeded]        TEXT           NULL,
    [BayRulesCount]            INT            NULL,
    [LastRefreshed]            NVARCHAR (200) NULL,
    [CoreTablesCreated]        INT            NULL,
    [Status]                   NVARCHAR (50)  NULL,
    [Cluster_ID]               INT            NULL
);


GO

