CREATE TABLE [dbo].[ReportVersionAttributes_BU_02042025] (
    [ReportID]                 INT            NOT NULL,
    [ReportOwner]              NVARCHAR (4)   NULL,
    [BranchNumber]             INT            NULL,
    [ReportName]               NVARCHAR (MAX) NULL,
    [PerfStartDate]            INT            NULL,
    [PerfEndDate]              INT            NULL,
    [MacroSpaceDate]           TEXT           NULL,
    [Cohort]                   NVARCHAR (MAX) NULL,
    [CohortStores]             SMALLINT       NULL,
    [BranchName]               NVARCHAR (MAX) NULL,
    [FullBaySize]              DECIMAL (5, 2) NULL,
    [RoundBaySize]             DECIMAL (5, 2) NULL,
    [UnitOfMeasure]            NVARCHAR (MAX) NULL,
    [DaysTrading]              INT            NULL,
    [ViewbyStoreTempcatDept]   NVARCHAR (MAX) NULL,
    [MinBaysforMaxRange]       CHAR (1)       NULL,
    [UseProductCube]           CHAR (1)       NULL,
    [UseTrend]                 CHAR (1)       NULL,
    [UseMinLMtr]               CHAR (1)       NULL,
    [UseMaxLMtr]               CHAR (1)       NULL,
    [IncNumberofProducts]      CHAR (1)       NULL,
    [PotentialSalesAdjustment] DECIMAL (5, 4) NULL,
    [CubeFlex]                 DECIMAL (5, 4) NULL,
    [TopHighlight]             DECIMAL (5, 4) NULL,
    [BottomHighlight]          DECIMAL (5, 4) NULL,
    [UnitSalesMix_UserSet]     FLOAT (53)     NULL,
    [ValueSalesMix_UserSet]    FLOAT (53)     NULL,
    [ProfitSalesMix_UserSet]   FLOAT (53)     NULL,
    [SalesLessWaste_UserSet]   FLOAT (53)     NULL,
    [SalesProfitMix_UserSet]   FLOAT (53)     NULL,
    [SalesMixCube_UserSet]     FLOAT (53)     NULL,
    [DOSCasePack_UserSet]      FLOAT (53)     NULL,
    [FixtureDensity_UserSet]   FLOAT (53)     NULL,
    [MixIncCohort_UserSet]     FLOAT (53)     NULL,
    [SpaceAdjustment]          DECIMAL (5, 4) NULL,
    [ElasticitySalesDiff]      DECIMAL (5, 4) NULL,
    [DensityMetric]            TEXT           NULL,
    [UMDID]                    CHAR (15)      NULL,
    [DoSDefault]               FLOAT (53)     NULL,
    [CasesDefault]             FLOAT (53)     NULL,
    [BayRoundingThreshold]     FLOAT (53)     NULL,
    [PerfDateExclusions]       NVARCHAR (MAX) NULL,
    [ExcludeCategories]        TEXT           NULL,
    [RefreshTypeNeeded]        TEXT           NULL,
    [BayRulesCount]            INT            NULL,
    [LastRefreshed]            NVARCHAR (200) NULL,
    [CoreTablesCreated]        INT            NULL,
    [Status]                   NVARCHAR (50)  NULL,
    [Cluster_ID]               INT            NULL
);
GO

