CREATE TABLE [dbo].[RVA] (
    [ReportID]                 FLOAT (53)    NULL,
    [ReportOwner]              VARCHAR (255) NULL,
    [BranchNumber]             FLOAT (53)    NULL,
    [ReportName]               VARCHAR (255) NULL,
    [PerfStartDate]            FLOAT (53)    NULL,
    [PerfEndDate]              FLOAT (53)    NULL,
    [MacroSpaceDate]           VARCHAR (255) NULL,
    [Cohort]                   VARCHAR (255) NULL,
    [CohortStores]             FLOAT (53)    NULL,
    [BranchName]               VARCHAR (255) NULL,
    [FullBaySize]              FLOAT (53)    NULL,
    [RoundBaySize]             FLOAT (53)    NULL,
    [UnitOfMeasure]            VARCHAR (255) NULL,
    [DaysTrading]              FLOAT (53)    NULL,
    [ViewbyStoreTempcatDept]   VARCHAR (255) NULL,
    [MinBaysforMaxRange]       VARCHAR (255) NULL,
    [UseProductCube]           VARCHAR (255) NULL,
    [UseTrend]                 VARCHAR (255) NULL,
    [UseMinLMtr]               VARCHAR (255) NULL,
    [UseMaxLMtr]               VARCHAR (255) NULL,
    [IncNumberofProducts]      VARCHAR (255) NULL,
    [PotentialSalesAdjustment] FLOAT (53)    NULL,
    [CubeFlex]                 FLOAT (53)    NULL,
    [TopHighlight]             FLOAT (53)    NULL,
    [BottomHighlight]          FLOAT (53)    NULL,
    [UnitSalesMix_UserSet]     FLOAT (53)    NULL,
    [ValueSalesMix_UserSet]    FLOAT (53)    NULL,
    [ProfitSalesMix_UserSet]   FLOAT (53)    NULL,
    [SalesLessWaste_UserSet]   FLOAT (53)    NULL,
    [SalesProfitMix_UserSet]   FLOAT (53)    NULL,
    [SalesMixCube_UserSet]     FLOAT (53)    NULL,
    [DOSCasePack_UserSet]      FLOAT (53)    NULL,
    [FixtureDensity_UserSet]   FLOAT (53)    NULL,
    [MixIncCohort_UserSet]     FLOAT (53)    NULL,
    [SpaceAdjustment]          FLOAT (53)    NULL,
    [ElasticitySalesDiff]      FLOAT (53)    NULL,
    [DensityMetric]            VARCHAR (255) NULL,
    [UMDID]                    VARCHAR (255) NULL,
    [DoSDefault]               FLOAT (53)    NULL,
    [CasesDefault]             FLOAT (53)    NULL,
    [BayRoundingThreshold]     FLOAT (53)    NULL,
    [PerfDateExclusions]       VARCHAR (255) NULL,
    [ExcludeCategories]        VARCHAR (255) NULL,
    [RefreshTypeNeeded]        VARCHAR (255) NULL,
    [BayRulesCount]            FLOAT (53)    NULL,
    [LastRefreshed]            VARCHAR (255) NULL,
    [CoreTablesCreated]        FLOAT (53)    NULL,
    [Status]                   VARCHAR (255) NULL,
    [Cluster_ID]               VARCHAR (255) NULL
);


GO

