environmentvariabledefinition:
  '@schemaname': osp_MSODB
  apiid: /providers/microsoft.powerapps/apis/shared_sql
  displayname:
    '@default': osp_MSODB
    label:
      '@description': osp_MSODB
      '@languagecode': 1033
  introducedversion: 5.5
  iscustomizable: 1
  isrequired: 0
  parameterkey: database
  parentdefinitionid:
    schemaname: osp_MSOServer
  secretstore: 0
  type: 100000004
